package com.yx.base.document.model;
// Generated 2017-6-7 12:07:25 by Hibernate Tools 5.2.1.Final

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * ImFeed generated by hbm2java
 */
@Document(collection = "ImBankRegion")
public class BankRegion implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 7346150423595088654L;
	@Id
	@GeneratedValue
	private Long id;
	private Long regionCode;
	private String regionName;
	private String regionLevel;
	private String regionBelong;
	private String regionProvince;	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Long getRegionCode() {
		return regionCode;
	}
	public void setRegionCode(Long regionCode) {
		this.regionCode = regionCode;
	}
	public String getRegionName() {
		return regionName;
	}
	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}
	public String getRegionLevel() {
		return regionLevel;
	}
	public void setRegionLevel(String regionLevel) {
		this.regionLevel = regionLevel;
	}
	public String getRegionBelong() {
		return regionBelong;
	}
	public void setRegionBelong(String regionBelong) {
		this.regionBelong = regionBelong;
	}
	public String getRegionProvince() {
		return regionProvince;
	}
	public void setRegionProvince(String regionProvince) {
		this.regionProvince = regionProvince;
	}

	
	

}
