package com.yx.base.document.model;
// Generated 2017-6-7 12:07:25 by Hibernate Tools 5.2.1.Final

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * ImFeed generated by hbm2java
 */
@Document(collection = "ImFeed")
public class Feed implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -7344268265428747844L;
	@Id
	@GeneratedValue
	private String id;
	private Long belongUserId;
	private String feedText;
	private String feedImgs;
	private Long userId;
	private String userName;
	private String userHeadUrl;
	private Long createTime;
	private Integer status;
	private long feedId;
	private String lat;
	private String lng;
	private String address;
	private String at;
	private String uids;
	private String feedVideo;
	private int priv;
	private String ext;
	public String getLat() {
		return lat;
	}
	public void setLat(String lat) {
		this.lat = lat;
	}
	public String getLng() {
		return lng;
	}
	public void setLng(String lng) {
		this.lng = lng;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getAt() {
		return at;
	}
	public void setAt(String at) {
		this.at = at;
	}
	public String getUids() {
		return uids;
	}
	public void setUids(String uids) {
		this.uids = uids;
	}
	public int getPriv() {
		return priv;
	}
	public void setPriv(int priv) {
		this.priv = priv;
	}
	
	@DBRef
	private List<FeedPraise> imFeedPraises =new ArrayList<FeedPraise>();
	private List<FeedComment> imFeedComments=new ArrayList<FeedComment>();
	private List<FeedUser> atUsers=new ArrayList<FeedUser>();
		
	
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getUserHeadUrl() {
		return userHeadUrl;
	}
	public void setUserHeadUrl(String userHeadUrl) {
		this.userHeadUrl = userHeadUrl;
	}
	public long getFeedId() {
		return feedId;
	}
	public void setFeedId(long feedId) {
		this.feedId = feedId;
	}
	public Long getBelongUserId() {
		return belongUserId;
	}
	public void setBelongUserId(Long belongUserId) {
		this.belongUserId = belongUserId;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getFeedText() {
		return feedText;
	}
	public void setFeedText(String feedText) {
		this.feedText = feedText;
	}
	public String getFeedImgs() {
		return feedImgs;
	}
	public void setFeedImgs(String feedImgs) {
		this.feedImgs = feedImgs;
	}
	public Long getUserId() {
		return userId;
	}
	public void setUserId(Long userId) {
		this.userId = userId;
	}
	public Long getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}
	public Integer getStatus() {
		return status;
	}
	public void setStatus(Integer status) {
		this.status = status;
	}
	public List<FeedPraise> getImFeedPraises() {
		return imFeedPraises;
	}
	public void setImFeedPraises(List<FeedPraise> imFeedPraises) {
		this.imFeedPraises = imFeedPraises;
	}
	public List<FeedComment> getImFeedComments() {
		return imFeedComments;
	}
	public void setImFeedComments(List<FeedComment> imFeedComments) {
		this.imFeedComments = imFeedComments;
	}
	public List<FeedUser> getAtUsers() {
		return atUsers;
	}
	public void setAtUsers(List<FeedUser> atUsers) {
		this.atUsers = atUsers;
	}
	public String getFeedVideo() {
		return feedVideo;
	}
	public void setFeedVideo(String feedVideo) {
		this.feedVideo = feedVideo;
	}
	public String getExt() {
		return ext;
	}
	public void setExt(String ext) {
		this.ext = ext;
	}

	

}
