package com.yx.base.document.model;
// Generated 2017-6-7 12:07:25 by Hibernate Tools 5.2.1.Final

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * ImFeed generated by hbm2java
 */
@Document(collection = "ImFriendGroup")
public class FriendGroup implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 649921621576689639L;
	@Id
	@GeneratedValue
	private String id;
	private Long belongUserId;
	private String groupName;
	private Long groupId;
	private Long createTime;
	
	@DBRef
	private List<FeedPraise> imFeedPraises =new ArrayList<FeedPraise>();
	private List<FeedComment> imFeedComments=new ArrayList<FeedComment>();
		
	
	public Long getBelongUserId() {
		return belongUserId;
	}
	public void setBelongUserId(Long belongUserId) {
		this.belongUserId = belongUserId;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	public Long getCreateTime() {
		return createTime;
	}
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}
	public List<FeedPraise> getImFeedPraises() {
		return imFeedPraises;
	}
	public void setImFeedPraises(List<FeedPraise> imFeedPraises) {
		this.imFeedPraises = imFeedPraises;
	}
	public List<FeedComment> getImFeedComments() {
		return imFeedComments;
	}
	public void setImFeedComments(List<FeedComment> imFeedComments) {
		this.imFeedComments = imFeedComments;
	}

	

}
